### ISSUE TITLE
Predictors

### ISSUE THREAD

**Issue by Exlonk** [jvalegre/robert#49]
I want only the descriptors so I use 

python -m aqme --csearch --program rdkit --input CSV_NAME.csv --sample 50

python -m aqme --qdescp --files "CSEARCH/*.sdf" --program xtb --csv_name CSV_NAME.csv

In the second step, I had to change the name of the column 'smiles' to 'SMILES'

![bug](https://github.com/user-attachments/assets/1521e8d4-3645-4574-81fe-241486af8d93)

Question: When I try to get only the descriptors I had to put the column "target" it constructs the predictors in function of the target?

Question: I try to use only the machine learning model with my own csv that I get from the previous step, some colums were lists and it didnt work, if I use only a csv file I can only use columns with numerical values?

**Comment by ddgunizar** [comment]
So right now you have two ways of obtaining the descriptors:

- Using directly the AQME program (which is what you’re currently doing)
- Using the AQME-ROBERT workflow (https://robert.readthedocs.io/en/latest/Examples/full_workflow/smiles_workflow.html); in this case, you need a target value because, after calculating the descriptors, ROBERT will run the ML workflow.

In response to the second question:

- The AQME-ROBERT.csv file should not contain columns with lists (try installing the latest version of AQME and regenerate the CSV).
- The csv document you use for ROBERT can contain both numerical and categorical values (by default, a one-hot encoding will be applied for the categorical ones).

**Comment by jvalegre** [comment]
Just to add up from the previous comment - AQME v1.6.1 (probably the version you're using) leaves columns with lists corresponding to atomic descriptors after running QDESCP. In the new version 1.7.0, these lists aren't created and it's easier to create descriptor databases. This v1.7.0 is currently available on GitHub and it should be soon available on pip/conda as well.

BTW please follow the standard templates for issues when possible, that way we can help users more efficiently (since we have versions, installation info, etc)

**Comment by Exlonk** [comment]
Your are very kind for your answers thanks a lot
